apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-tools
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: security-tools
      name: securitytools
    spec:
      containers:
      - image: bkauf/gcpdemo
        env:
        - name: CLOUD
          value: "gcp"
        imagePullPolicy: Always
        name: webserver
        ports:
        - containerPort: 8080
          name: frontend
       
